/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router';

// Import Routes

import { Route as rootRoute } from './routes/__root';

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')();
const MilestonesIndexLazyImport = createFileRoute('/milestones/')();

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route));

const MilestonesIndexLazyRoute = MilestonesIndexLazyImport.update({
  path: '/milestones/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/milestones/index.lazy').then((d) => d.Route),
);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexLazyImport;
      parentRoute: typeof rootRoute;
    };
    '/milestones/': {
      id: '/milestones/';
      path: '/milestones';
      fullPath: '/milestones';
      preLoaderRoute: typeof MilestonesIndexLazyImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  MilestonesIndexLazyRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/milestones/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/milestones/": {
      "filePath": "milestones/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
